import sys
import os
import random
from time import sleep
from os import system, name

#Variaveis Iniciais
vida = 100
xp = 0
dinheiro = 0
condicaoJogador = True

def checkVida():
    if vida <= 0:
        sleep(6)
        clear()
        print('GAME OVER!')
        print()
        print()
        sleep(1)
        print('Sua vida chegou a zero, recomece o jogo.')
        sleep(5)
        sys.exit()

def clear():
    if name == 'nt': 
        _ = system('cls')

def mostraInfo():
    print('Vida:            ', vida)
    print('Pontos de XP:    ', xp)
    print('Dinheiro:        ', dinheiro)

#def tutorial():

clear()
sleep(1)
print('Bem-Vindo Ao Jogo Cyberpunk 2076')
sleep(3)
print()
print('Primeiramente gostariamos de saber seu nome:')
nome = input()
sleep(1)
print()
clear()
print('{}, seja bem-vindo ao Cyberpunk 2076'.format(nome))
sleep(2)
print()
print('Vamos começar!')
print()
print('1) Começar')
print('2) Tutorial')
print('3) Sair')
print()

print('O que deseja fazer?')
print()

def cap1():
    clear()
    print('CAPITULO 1: INTRODUÇÃO')
    sleep(4)
    print()
    print()
    print('<Narrador>', '{}'.format(nome),'você está na cidade de Saint Paul na Califórnia.')
    print()
    sleep(4)
    print('<Narrador> Você é um policial que trabalha no Departamento de Policia de Saint Paul, e foi transferido para o Distrito 22.')
    print()
    sleep(3)
    print('<Narrador> O comandante Gordon, seu novo capitão, te espera na sala dele no 6° andar, ele vai te apresentar seu novo parceiro.')
    print()
    sleep(4)
    print('<Narrador> Agora você irá para o 6° andar.')
    print()
    sleep(4)
    print()
    sleep(5)
    print('/'*90)
    print('LOADING...')
    print('/'*90)
    print()
    sleep(2)
    print('<Narrador> Você está no 6° andar.')
    print()
    sleep(2)
    print()
    print('<Gordon> -Olá, sou o comandante Gordon. Seja bem vindo a minha unidade.')
    print()
    sleep(2)
    print('<Gordon> -Está na hora de conhecer seu parceiro...')
    print()
    sleep(2)
    print('<Gordon> -Esse é o Steve, transferido do Distrito 30.')
    print()
    sleep(2)
    print('<Steve> -Prazer em te conhecer, sou o Steve.')
    print()
    sleep(2)
    print('<Steve> -Sei que juntos vamos fazer um grande trabalho.')
    print()
    sleep(3)
    print("/"*90)
    print('<Narrador> Após 2 anos de trabalho, {} recebe uma missão que irá mudar sua carreira...'.format(nome))
    print("/"*90)
    sleep(4)
    print()
    print('<Gordon> -Bom dia {}, tenho tarefa muito importante para você, que determinará sua nova função aqui.'.format(nome))
    print()
    sleep(3)
    print('<Gordon> -Uma facção criminosa anda fazendo muitos assaltos no bairro Round Capon.')
    print()
    sleep(3)
    print('<Gordon> -Preciso que você faça uma abordagem e pare estes criminosos rápido.')
    print()
    sleep(3)
    print('<Gordon> -Quando a tarefa estiver concluída conversamos sobre sua promoção.')
    print()
    sleep(3)
    print('<Gordon> -Uma viatura te espera na saída do prédio.')
    print()
    sleep(3)

comando = int(input())
if comando == 1:
    cap1()
elif comando == 2:
    print('Tutorial:')
    print()
    sleep(3)
    print('1 - Para jogar basta usar o teclado e digitar o número da ação escolhida.')
    sleep(1)
    print('2 - Com o avançar de cada capítulo você ganhará dinheiro.')
    sleep(1)
    print('3 - Após avançar cada capítulo você terá a opção de comprar o encremnto de atributos na loja por meio de dinheiro.')
    sleep(1)
    print('4 - Os atributos do jogo são: XP, Vida e Dinheiro.')
    sleep(1)
    print('5 - Não deixe a vida de seu pesonagem chegar a 0.')
    sleep(1)
    print('6 - No final do jogo você terá uma avaliação do seu desempenho.')
    sleep(1)
    print('7 - Cada linha de diálogo demora em média 3 segundos para aparecer, então não aperte nenhuma tecla até a linha ser executada.')
    sleep(1)
    print('8 - Divirta-se.')
    sleep(2)
    cap1()
elif comando == 3:
    sys.exit()

clear()
sleep(5)
print('/'*90)
print('LOADING...')
print('/'*90)
print()
sleep(6)
clear()

#Se a a condicao eh true ent o jogador ta vivo
condicaoJogador = True
#loop capitulo 2
while condicaoJogador == True:
    clear()
    print('CAPITULO 2: A MISSÃO')
    print()
    print()
    sleep(4)
    print('<Narrador> O batalhão do distrito 22 está investigando o organização que coordena as operações criminosas na área.')
    sleep(6)
    print()
    print('<Narrador> Sua missão será liderar esse esquadrão em uma missão para prender os ladrões que estão planejando um assalto ao banco.')
    sleep(6)
    print()
    print('<Narrador> Você agora irá se reunir com os integrantes do batalhão para decidir a sua estratégia.')
    sleep(5)
    clear()
    print('<Narrador> Agora você está se dirigindo para a viatura.')
    print()
    sleep(5)
    clear()
    print('/'*90)
    print('LOADING...')
    print('/'*90)
    print()
    sleep(5)
    clear()
    print('<Narrador> Você está reunido com a sua equipe próximo ao banco.')
    print()
    sleep(3)
    #situacao 1
    print('<Narrador> Está na hora de escolher a sua estratégia:')
    print()
    sleep(2)
    print('1) Esperar o assalto começar e invadir com sua equipe pela entrada principal.')
    print('2) Esperar os assaltantes fugir para correr atrás deles.')
    print('3) Fechar a área após a entrada dos bandidos.')
    print()
    decisao = int(input())
    clear()
    print('/'*90)
    print('Na hora do assalto....')
    print('/'*90)
    sleep(3)
    clear()
    if decisao == 1:
        print('<{}> -Certo rapazes entrar ao meu comando...'.format(nome))
        for c in range(3, -1, -1):
            sleep(1)
            print(c)
        print('<{}> -Agora!!! Vamos invadir!'.format(nome))
        print()
        sleep(3)
        print('<Narrador> Sua equipe invadiu com sucesso, porém um de seus policiais morreu.')
        xp = xp + 5
        print()
        sleep(3)
        print('<Narrador> Os assaltantes estão atirando em você e na sua equipe.')
        print()
        sleep(3)
        #situacao 2
        print('<Narrador> Você agora deve decidir o que a sua equipe deve fazer:')
        print()
        sleep(3)
        print('1) Avançar para cima dos banidos.')
        print('2) Buscar cobertura para atirar.')
        print()
        decisaox = int(input())
        if decisaox == 1:
            vida = vida - 20
            print()
            sleep(3)
            print('<Narrador> Você levou um tiro e perdeu 20 de vida.')
            print()
            sleep(3)
            print('<Narrador> Com esse avanço você matou dois assaltantes, ganhando 40 Pontos de Experiência, porém dois policiais morreram.')
            checkVida()
        elif decisaox == 2:
            print()
            sleep(3)
            print('<Narrador> Você alcançou a cobertura com sucesso, não levou dano.')
            print()
            sleep(3)
            print('<Narrador> Com essa cobertura você conseguiu derrubar um dos assaltantes, ganhando 20 pontos de experiência.')
            xp = xp + 20
            print()
            sleep(3)
            print('<Narrador> Ao perceber que estava em menor número, você chamou os reforços e após alguns minutos eles chegaram e conseguiram prender os assaltantes com sucesso.')
            sleep(3)
    elif decisao == 2:
        print('<Narrador> Os assaltantes fugiram do banco ás pressas e agora você vai ter que persegui-los.')
        print()
        sleep(3)
        print('<Narrador> A perseguição continua e agora você terá que escolher entre...')
        print()
        sleep(3)
        #situacao 3
        print('1)Atirar com a viatura em movimento, com uma alta velocidade')
        print('2)Optar por um caminho alternativo para tentar fechar os criminosos e aborda-los')
        print()
        decisaox = int(input())
        if decisaox == 1 :
            xp = xp + 10
            vida = vida - 10
            print()
            sleep(3)
            print('<Narrador> Você acertou um civil, e perderá 10 de Xp')
            print()
            sleep(3)
            print('<Narrador> Você levou um tiro na perseguição, e perderá 10 de Vida')
            print()
            sleep(3)
            print('<Narrador> Porém com esse tiro, você acertou um dos assaltantes, fazendo com que o carro parasse')
            checkVida()
        elif decisaox == 2 :
            xp = xp + 20
            vida = vida - 20
            print()
            sleep(3)
            print('<Narrador> Você tomou um tiro no joelho durante a abordagem e perdeu 20 de vida')
            print()
            sleep(3)
            print('<Narrador> Os criminosos foram abordados e levados à delegacia do distrito 22')
            checkVida()
    elif decisao == 3:
        print('<Narrador> Os policias fecham o local através de uma doma de energia envolta do banco com os assaltantes.')
        print()
        sleep(3)
        print('<Narrador> Após fechar o perímetro do banco os assaltantes fazem reféns.')
        print()
        sleep(3)
        #situacao 4
        print('1) Tentar negociar com os criminosos.')
        print('2) Tentar fazer os assaltantes se renderem a força.')
        print()
        decisaox = int(input())
        if decisaox == 1:
            dinheiro = dinheiro + 20
            xp = xp + 50
            print()
            sleep(3)
            print('<Narrador> Após negociar com os criminosos você consegue liberar os reféns com sucesso.')
            print()
            sleep(3)
            print('<Narrador> Como recompensa por ter feito a escolha você recebe 20 unidades a mais.')
            sleep(3)
        elif decisaox == 2:
            xp = xp + 10
            vida = vida - 20
            print('<Narrador> Você consegue liberar quase todos os reféns.')
            print()
            sleep(3)
            print('<Narrador> Porém ao tentar fazer os criminosos se renderem a força, você acabou fazendo que um refén seja morto.')
            print()
            sleep(3)
            print('<Narrador> Você acaba perdendo 20 de vida, pois acaba levando um tiro no processo.')
            checkVida()
    sleep(3)
    print()
    print('<Narrador> Após todos os acontecimentos você conseguiu parar o assalto.')
    print()
    sleep(3)
    print('<Narrador> MISSAO CONCLUIDA!')
    sleep(6)
    condicaoJogador = False

#HUB
clear()
sleep(1)
print('HUB')
print()
sleep(1)
mostraInfo()
print()
sleep(1)
print('1) Continuar')
print('2) Loja')
print('3) Sair')
print()
decisao = int(input())
precoVida = 100 - vida
if decisao == 1:
    sleep(1)
    clear()
    condicaoJogador = True
elif decisao == 2 and dinheiro >= precoVida and dinheiro >= 50:
    sleep(1)
    a = True
    #Inicializacao da Loja
    while (a == True and vida < 100) or (a == True and dinheiro >= 50) or (a == True and dinheiro >= precoVida):
        precoVida = 100 - vida
        clear()
        print('HUB --- Loja')
        print()
        sleep(1)
        mostraInfo()
        print()
        sleep(1)
        print('1) Completar vida --- {} unidades'.format(precoVida))
        print('2) Comprar 50 XP ---- 50 unidades')
        print('3) VOLTAR')
        print()
        decisaox = int(input())
        if decisaox == 1 and dinheiro >= precoVida and vida < 100:
            dinheiro = dinheiro - precoVida
            vida = vida + precoVida
            sleep(1)
            print()
            print('Pronto!')
            sleep(2)
        elif decisaox == 1 and vida >= 100:
            sleep(2)
            print()
            print('Sua vida esta cheia.')
            sleep(4)
        elif decisaox == 2 and dinheiro >= 50:
            dinheiro = dinheiro - 50
            xp = xp + 50
            print()
            sleep(1)
            print('Pronto!')
            sleep(2)
        elif decisaox == 2 or decisaox == 3 and dinheiro < precoVida and dinheiro < 50:
            clear()
            print('HUB')
            print()
            sleep(1)
            print('Você não tem dinheiro o suficiente para usar a loja. Volte após o próximo capítulo.')
            print()
            sleep(2)
            mostraInfo()
            sleep(1)
            print('1) Continuar o Jogo')
            print('2) Sair do Jogo')
            print()
            decisaoy = int(input())
            if decisaoy == 1:
                a = False
                sleep(1)
                clear()
                condicaoJogador = True
            elif decisaoy == 2:
                sleep(2)
                sys.exit()

        elif decisaox == 3:
            clear()
            print('HUB')
            print()
            sleep(1)
            mostraInfo()
            sleep(1)
            print()
            print('1) Continuar o Jogo')
            print('2) Sair do Jogo')
            print()
            decisaoy = int(input())
            if decisaoy == 1:
                a = False
                sleep(1)
                clear()
                condicaoJogador = True
            elif decisaoy == 2:
                sleep(2)
                sys.exit()
#Condicoes caso o jogador nao possa acessar a loja
elif (decisao == 2 and dinheiro < precoVida) or (decisao == 2 and dinheiro < 50):
    clear()
    print('HUB')
    print()
    sleep(2)
    print('Você não tem dinheiro o suficiente para usar a loja. Volte após o próximo capítulo.')
    print()
    sleep(1)
    mostraInfo()
    sleep(1)
    print()
    print('1) Continuar o Jogo')
    print('2) Sair do Jogo')
    print()
    decisaoy = int(input())
    if decisaoy == 1:
        a = False
        sleep(1)
        clear()
        condicaoJogador = True
    elif decisaoy == 2:
        sleep(2)
        sys.exit()
elif decisao == 3:
    sleep(2)
    sys.exit()

while condicaoJogador == True:
    clear()
    sleep(3)
    print('Capítulo 3: STEVE E A PROMOÇÃO')
    print()
    print()
    sleep(4)
    print('<Narrador> Após sua última missão você decide voltar para a unidade do batalhão 22 para conversar com Gordon.')
    print()
    sleep(4)
    print('/'*90)
    print('LOADING... Indo para a unidade do batalhão 22.')
    print('/'*90)
    print()
    sleep(2)
    print('<Narrador> Você entra na sala do Gordon.')
    print()
    sleep(2)
    print('<Gordon> -Seja bem vindo novamente {}. Tenho uma novidade para você!'.format(nome))
    print()
    sleep(3)
    print('<Gordon> -Pelo seu último desempenho decidi te dar uma promoção, agora você será detetive.')
    print()
    sleep(3)
    print('<Narrador> Agora que você é detetive, Meus parabéns com isso você ganha 120 unidades.')
    dinheiro = dinheiro + 120
    print()
    sleep(2)
    print('<Narrador> Com a sua promoção você lidera um esquadrão e comanda patrulhas pela cidade.')
    print()
    sleep(3)
    print('/'*90)
    print('LOADING... Passam 2 dias')
    print('/'*90)
    print()
    sleep(2)
    print('<Steve> -{},eu tenho um plano para parar o cartel de drogas da Zona Oeste:'.format(nome))
    print()
    sleep(3)
    print('<Steve> -Minhas fontes dizem que chefe da organização criminosa "CCQ" estará na favela "Little Farm" para fazer um acordo com gangues rivais.')
    print()
    sleep(4)
    print('<Steve> -É uma oportunidade perfeita!')
    print()
    sleep(3)
    print('/'*90)
    print('LOADING... Você junto de sua unidade estão indo para a favela "Little Farm" fazer a próxima missão.')
    print('/'*90)
    print()
    sleep(3)
    print('Você está na entrada da comunidade')
    print()
    sleep(3)
    print('A CCQ é avistada negociando o contrabando de nano chips quânticos.')
    print()
    sleep(3)
    print('<Narrador> Está na hora de escolher sua estratégia para iniciar o combate.')
    print()
    sleep(3)
    print('1) Entrar atirando logo pela entrada.')
    print('2) Se infiltrar na comunidade.')
    print('3) Esperar a CCQ na entrada da periferia.')
    print()
    decisao = int(input())
    print()
    print('/'*90)
    print('Início da operação....')
    print('/'*90)
    print()
    sleep(1)
    if decisao == 1:
        xp = xp + 10
        vida = vida - 20
        dinheiro = dinheiro + 20
        print('<Narrador> Você entra com seu batalhão atirando.')
        print()
        sleep(3)
        print('<Narrador> A CCQ já estava te esperando. Eles armaram uma armadilha.')
        print()
        sleep(3)
        print('<Narrador> Durante o processo inocentes morrem e seu batalhão é contra-atacado.')
        print()
        sleep(3)
        print('<Narrador> Vocês conseguem matar o chefe da CCQ')
        print()
        sleep(3)
        print('<Narrador> Você leva um tiro no ombro, perde 20 pontos de vida, ganha apenas 10 pontos de xp e ganha 20 unidades.')
        checkVida()
    elif decisao == 2:
        xp = xp + 50
        dinheiro = dinheiro + 75
        print('<Narrador> Seu batalhão se infiltra na favela.')
        print()
        sleep(3)
        print('<Narrador> A CCQ já estava te esperando. Eles armaram uma armadilha.')
        print()
        sleep(3)
        print('<Narrador> Durante o processo vcs conseguem matar o chefe.')
        print()
        sleep(3)
        print('<Narrador> Nenhum inocente é morto durante a operação.')
        print()
        sleep(3)
        print('<Narrador> Você ganhou 50 pontos de xp e 75 unidades.')
    elif decisao == 3:
        xp = xp + 20
        vida = vida - 10
        dinheiro = dinheiro + 50
        print('<Narrador> Seu batalhão espera a CCQ do lado de fora da periferia.')
        print()
        sleep(3)
        print('<Narrador> A CCQ já estava te esperando. Eles armaram uma armadilha.')
        print()
        sleep(3)
        print('<Narrador> Durante o processo vocês conseguem matar o chefe e nenhum inocente é morto.')
        print()
        sleep(3)
        print('<Narrador> Acontece um tiroteio na entrada da favela e você acaba capotando o carro.')
        print()
        sleep(3)
        print('<Narrador> Você perde 10 pontos de vida e ganha 20 pontos de xp.')
        print('<Narrador> Por matar o chefe você ganha 50 unidades.')
        checkVida()
        print()
        sleep(3)
    print()
    sleep(3)
    print('<Narrador> A operação acaba e sua equipe decide voltar para o distrito 22.')
    print()
    sleep(3)
    print('<Narrador> De repente vocês são surpreendidos por 2 carros pretos que atiram contra seu batalhão.')
    print()
    sleep(3)
    print('<Narrador> Steve é atingido na cabeça e acaba morrendo na hora.')
    print()
    sleep(3)
    print('<Narrador> A ação foi muito rapida, não deu tempo de revidar o ataque. Vocês acabam voltando para unidade com o Steve morto.')
    print()
    sleep(6)
    condicaoJogador = False

#HUB cap 3
clear()
sleep(1)
print('HUB')
print()
sleep(1)
mostraInfo()
print()
sleep(1)
print('1) Continuar')
print('2) Loja')
print('3) Sair')
print()
decisao = int(input())
precoVida = 100 - vida
if decisao == 1:
    sleep(1)
    clear()
    condicaoJogador = True
elif decisao == 2 and dinheiro >= precoVida and dinheiro >= 50:
    sleep(1)
    a = True
    #Inicializacao da Loja
    while (a == True and vida < 100) or (a == True and dinheiro >= 50) or (a == True and dinheiro >= precoVida):
        precoVida = 100 - vida
        clear()
        print('HUB --- Loja')
        print()
        sleep(1)
        mostraInfo()
        print()
        sleep(1)
        print('1) Completar vida --- {} unidades'.format(precoVida))
        print('2) Comprar 50 XP ---- 50 unidades')
        print('3) VOLTAR')
        print()
        decisaox = int(input())
        if decisaox == 1 and dinheiro >= precoVida and vida < 100:
            dinheiro = dinheiro - precoVida
            vida = vida + precoVida
            sleep(1)
            print()
            print('Pronto!')
            sleep(2)
        elif decisaox == 1 and vida >= 100:
            sleep(2)
            print()
            print('Sua vida esta cheia.')
            sleep(4)
        elif decisaox == 2 and dinheiro >= 50:
            dinheiro = dinheiro - 50
            xp = xp + 50
            print()
            sleep(1)
            print('Pronto!')
            sleep(2)
        elif decisaox == 2 or decisaox == 3 and dinheiro < precoVida and dinheiro < 50:
            clear()
            print('HUB')
            print()
            sleep(1)
            print('Você não tem dinheiro o suficiente para usar a loja. Volte após o próximo capítulo.')
            print()
            sleep(2)
            mostraInfo()
            sleep(1)
            print()
            print('1) Continuar o Jogo')
            print('2) Sair do Jogo')
            print()
            decisaoy = int(input())
            if decisaoy == 1:
                a = False
                sleep(1)
                clear()
                condicaoJogador = True
            elif decisaoy == 2:
                sleep(2)
                sys.exit()

        elif decisaox == 3:
            clear()
            print('HUB')
            print()
            sleep(1)
            mostraInfo()
            sleep(1)
            print()
            print('1) Continuar o Jogo')
            print('2) Sair do Jogo')
            print()
            decisaoy = int(input())
            if decisaoy == 1:
                a = False
                sleep(1)
                clear()
                condicaoJogador = True
            elif decisaoy == 2:
                sleep(2)
                sys.exit()
#Condicoes caso o jogador nao possa acessar a loja
elif (decisao == 2 and dinheiro < precoVida) or (decisao == 2 and dinheiro < 50):
    clear()
    print('HUB')
    print()
    sleep(2)
    print('Você não tem dinheiro o suficiente para usar a loja. Volte após o próximo capítulo.')
    print()
    sleep(1)
    mostraInfo()
    sleep(1)
    print()
    print('1) Continuar o Jogo')
    print('2) Sair do Jogo')
    print()
    decisaoy = int(input())
    sleep(3)
    if decisaoy == 1:
        a = False
        sleep(1)
        clear()
        condicaoJogador = True
    elif decisaoy == 2:
        sleep(2)
        sys.exit()
elif decisao == 3:
    sleep(2)
    sys.exit()

while condicaoJogador == True:
    print('CAPITULO 4: A BUSCA POR RESPOTAS')
    print()
    print()
    sleep(3)
    print('<Narrador> Com o Steve morto, restou a {} procurar por mais respostas sobre o assasinato de seu parceiro.'.format(nome))
    print()
    sleep(3)
    print('<Gordon> -Bom dia {}, estou reunindo uma equipe para buscar informações sobre o paradeiro do assasino do Steve.'.format(nome))
    print()
    sleep(3)
    print('<Gordon> --Estou indo para o térreo para agrupar a equipe e seguir para o local do crime.')
    print()
    clear()
    print('/'*90)
    print('A caminho da cena do crime...')
    print('/'*90)
    print()
    sleep(5)
    print('<Narrador> A investigação começa e {} junto de Gordon começam a procurar pistas.'.format(nome))
    print()
    sleep(3)
    print('<Gordon> -Chegamos {}, quer começar por onde ?'.format(nome))
    print()
    sleep(3)
    print('1) Ver as marcas de pneu nas proximidades.')
    print('2) Observar as capsulas de balas no asfalto.')
    print('3) Ver as filmagens das câmeras locais.')
    print()
    decisao = int(input())
    if decisao == 1:
        print()
        sleep(2)
        print('<Gordon> -As marcas de pneu estão direcionadas para um beco ruas próximas.')
        print()
        sleep(2)
        print('<Gordon> -Eles provavelmente entraram em algum depósito para se esconder.')
        print()
        sleep(4)
        print('<Narrador> Vamos verificar o que agora ?')
        print()
        print('1) Observar as capsulas de bala no asfalto.')
        print('2) Ver as filmagens das câmeras locais.')
        print()
        decisao1 = int(input())
        if decisao1 == 1:
            print()
            sleep(2)
            print('<Gordon> -As cápsulas são de armaneto militar e só facções envolvidas no mercado de fluidos de nanochips ilegais conseguem este armamento.')
            print()
            sleep(2)
            print('<{}> -O assasinato pareceu coordenado e objetivo, a unica vítima foi Steve.'.format(nome))
            print()
            sleep(4)
            print('<Gordon> -Isto é do fetio de facções organizadas.')
            print()
            sleep(2)
            print('<Gordon> -Vamos observar as câmeras de segurança agora.')
            print()
            sleep(2)
            print('<Narrador> Nas câmeras {} e Gordon observaram o carro dos assasinos entrando em um depósito à dois quarteirões do local.'.format(nome))
            print()
            sleep(4)
            print('<Gordon> -Eles devem estar coordenando as operações no depósito ! Vamos abordar e fazer uma limpa no local, chamem reforços.')
            print()
            sleep(2)

        elif decisao1 == 2:
            print('<Gordon> -Vamos observar as câmeras de segurança agora.')
            print()
            sleep(2)
            print('<Narrador> Nas câmeras {} e Gordon observaram o carro dos assasinos entrando em um depósito à dois quarteirões do local.'.format(nome))
            print()
            sleep(4)
            print('<Gordon> -Eles devem estar coordenando as operações no depósito ! Vamos abordar e fazer uma limpa no local, chamem reforços.')
            print()
            sleep(2)
            print('<Gordon> -Antes de disso, vamos observar as cápsulas de bala no asfalto.')
            print()
            sleep(2)
            print('<Gordon> -As cápsulas são de armaneto militar e só facções envolvidas no mercado de fluidos de nanochips ilegais conseguem este armamento.')
            print()
            sleep(4)
            print('<{}> -O assasinato pareceu coordenado e objetivo, a unica vítima foi Steve.'.format(nome))
            print()
            sleep(2)
            print('<Gordon> -Isto é do fetio de facções organizadas.')
            print()
            sleep(4)

    elif decisao == 2:
        print()
        sleep(2)
        print('<Gordon> -As cápsulas são de armaneto militar e só facções envolvidas no mercado de fluidos de nanochips ilegais conseguem este armamento.')
        print()
        sleep(2)
        print('<{}> -O assasinato pareceu coordenado e objetivo, a unica vítima foi Steve.'.format(nome))
        print()
        sleep(4)
        print('<Gordon> -Isto é do fetio de facções organizadas.')
        print()
        sleep(2)
        print('<Narrador> O que fazer:')
        print()
        print('1) Ver as marcas de pneu nas proximidades')
        print('2) Ver as filmagens das câmeras locais.')
        decisao2 = int(input())
        if decisao2 == 1:
            print()
            sleep(4)
            print('<Gordon> -As marcas de pneu estão direcionadas para um beco ruas próximas.')
            print()
            sleep(2)
            print('<Gordon> -Eles provavelmente entraram em algum depósito para se esconder.')
            print()
            sleep(2)
            print('<Gordon> -Vamos observar as câmeras de segurança agora.')
            print()
            sleep(4)
            print('<Narrador> -Nas câmeras {} e Gordon observaram o carro dos assasinos entrando em um depósito à dois quarteirões do local.'.format(nome))
            print()
            sleep(2)
            print('<Gordon> -Eles devem estar coordenando as operações no depósito ! Vamos abordar e fazer uma limpa no local, chamem reforços.')
            print()
            sleep(2)

        elif decisao2 == 2:
            print('<Gordon> -Vamos observar as câmeras de segurança agora.')
            print()
            sleep(4)
            print('<Narrador> Nas câmeras {} e Gordon observaram o carro dos assasinos entrando em um depósito à dois quarteirões do local'.format(nome))
            print()
            sleep(2)
            print('<Gordon> -Eles devem estar coordenando as operações no depósito ! Vamos abordar e fazer uma limpa no local, chamem reforços.')
            print()
            sleep(2)
            print('<Gordon> -Mas antes vamos ver as marcas de pneu.')
            print()
            sleep(4)
            print('<Gordon> -As marcas de pneu estão em direção a um beco próximo.')
            print()
            sleep(2)
            print('<Gordon> -Eles devem ter entrado no depósito para se esconder !')
            print()
            sleep(2)

    elif decisao == 3:
        print('<Gordon> -Vamos observar as câmeras de segurança agora.')
        print()
        sleep(4)
        print('<Narrador> Nas câmeras {} e Gordon observaram o carro dos assasinos entrando em um depósito à dois quarteirões do local.'.format(nome))
        print()
        sleep(2)
        print('<Gordon> -Eles devem estar coordenando as operações no depósito !')
        print()
        sleep(2)
        print('<Narrador> Vamos investigar aonde agora ?.')
        print()
        sleep(1)
        print('1) Ver as marcas de pneu nas proximidades.')
        print('2) Observar as capsulas de bala no asfalto.')
        print()
        decisao3 = int(input())
        if decisao3 == 1:
            print('<Gordon> -As marcas de pneu estão direcionadas para um beco ruas próximas.')
            print()
            sleep(4)
            print('<Gordon> -Eles provavelmente entraram em algum depósito para se esconder.')
            print()
            sleep(2)
            print('<Gordon> -Vamos ver as cápsulas de bala agora.')
            print()
            sleep(2)
            print('<Gordon> -As cápsulas são de armaneto militar e só facções envolvidas no mercado de fluidos de nanochips ilegais conseguem este armamento.')
            print()
            sleep(2)
            print('<{}> -O assasinato pareceu coordenado e objetivo, a unica vítima foi Steve.'.format(nome))
            print()
            sleep(4)
            print('<Gordon> -Isto é do fetio de facções organizadas.')
            print()
            sleep(2)
            print('<Gordon> -Vamos fazer a limpa no depósito !')
            print()
            sleep(2)
           
        elif decisao3 == 2:
            print('<Gordon> -As cápsulas são de armaneto militar e só facções envolvidas no mercado de fluidos de nanochips ilegais conseguem este armamento.')
            print()
            sleep(4)
            print('<{}> -O assasinato pareceu coordenado e objetivo, a unica vítima foi Steve.'.format(nome))
            print()
            sleep(2)
            print('<Gordon> -Isto é do fetio de facções organizadas.')
            print()
            sleep(2)
            print('<Gordon> -Vamos ver as marcas de pneu agora.')
            print()
            sleep(4)
            print('<Gordon> -As marcas de pneu estão direcionadas para um beco ruas próximas.')
            print()
            sleep(2)
            print('<Gordon> -Eles provavelmente entraram em algum depósito para se esconder.')
            print()
            sleep(2)
    sleep(3)
    print('/'*90)
    print('LOADING...Entrando no depósito.')
    print('/'*90)
    sleep(3)
    condicaoJogador = False

clear()
sleep(1)
print('HUB')
print()
sleep(1)
mostraInfo()
print()
sleep(1)
print('1) Continuar')
print('2) Loja')
print('3) Sair')
print()
decisao = int(input())
precoVida = 100 - vida
if decisao == 1:
    sleep(1)
    clear()
    condicaoJogador = True
elif decisao == 2 and dinheiro >= precoVida and dinheiro >= 50:
    sleep(1)
    a = True
    #Inicializacao da Loja
    while (a == True and vida < 100) or (a == True and dinheiro >= 50) or (a == True and dinheiro >= precoVida):
        precoVida = 100 - vida
        clear()
        print('HUB --- Loja')
        print()
        sleep(1)
        mostraInfo()
        print()
        sleep(1)
        print('1) Completar vida --- {} unidades'.format(precoVida))
        print('2) Comprar 50 XP ---- 50 unidades')
        print('3) VOLTAR')
        print()
        decisaox = int(input())
        if decisaox == 1 and dinheiro >= precoVida and vida < 100:
            dinheiro = dinheiro - precoVida
            vida = vida + precoVida
            sleep(1)
            print()
            print('Pronto!')
            sleep(2)
        elif decisaox == 1 and vida >= 100:
            sleep(2)
            print()
            print('Sua vida esta cheia.')
            sleep(4)
        elif decisaox == 2 and dinheiro >= 50:
            dinheiro = dinheiro - 50
            xp = xp + 50
            print()
            sleep(1)
            print('Pronto!')
            sleep(2)
        elif decisaox == 2 or decisaox == 3 and dinheiro < precoVida and dinheiro < 50:
            clear()
            print('HUB')
            print()
            sleep(1)
            print('Você não tem dinheiro o suficiente para usar a loja. Volte após o próximo capítulo.')
            print()
            sleep(2)
            mostraInfo()
            sleep(1)
            print()
            print('1) Continuar o Jogo')
            print('2) Sair do Jogo')
            print()
            decisaoy = int(input())
            if decisaoy == 1:
                a = False
                sleep(1)
                clear()
                condicaoJogador = True
            elif decisaoy == 2:
                sleep(2)
                sys.exit()

        elif decisaox == 3:
            clear()
            print('HUB')
            print()
            sleep(1)
            mostraInfo()
            sleep(1)
            print()
            print('1) Continuar o Jogo')
            print('2) Sair do Jogo')
            print()
            decisaoy = int(input())
            if decisaoy == 1:
                a = False
                sleep(1)
                clear()
                condicaoJogador = True
            elif decisaoy == 2:
                sleep(2)
                sys.exit()
#Condicoes caso o jogador nao possa acessar a loja
elif (decisao == 2 and dinheiro < precoVida) or (decisao == 2 and dinheiro < 50):
    clear()
    print('HUB')
    print()
    sleep(2)
    print('Você não tem dinheiro o suficiente para usar a loja. Volte após o próximo capítulo.')
    print()
    sleep(1)
    mostraInfo()
    sleep(1)
    print()
    print('1) Continuar o Jogo')
    print('2) Sair do Jogo')
    print()
    decisaoy = int(input())
    if decisaoy == 1:
        a = False
        sleep(1)
        clear()
        condicaoJogador = True
    elif decisaoy == 2:
        sleep(2)
        sys.exit()
elif decisao == 3:
    sleep(2)
    sys.exit()

#CAP 5
while condicaoJogador == True:
    print('CAPITULO 5: FINAL')
    print()
    print()
    sleep(3)
    print('<Narrador> Após vocês entrarem no depósito, se deparam um homem grande e fortemente armado.')
    print()
    sleep(3)
    print('<Narrador> Qual ação você tomará:')
    print()
    sleep(1)
    #variaveis do chefe
    vidaChefe = 150
    def checkVidaChefe():
        import sys
        if vidaChefe <= 0:
            sleep(6)
            clear()
            #PONTUAÇÃO
            if xp >= 200:
                print('<Narrador> Parabens! Você foi muito bem !!')
            elif xp < 200 or xp > 150:
                print('<Narrador> Seu desempenho foi mediano')
            else:
                print('<Narrador> Seu desempenho foi ruim...')
            sys.exit()
    print('1) Conversar')
    print('2) Intimidar')
    print()
    decisao0 = int(input())
    if decisao0 == 1:
        print()
        sleep(2)
        print('<Desconhecido> -Estava com o pressentimento de que você iria vir até mim querendo ou não.')
        print()
        sleep(1)
        print('<Desconhecido> -Meu nome é PocketSquid.')
        print()
        sleep(2)
        print('<PoketSquid> -E eu confesso ter matado Steve como forma de vingança pela policia ter interferido nos meus negócios.')
        print()
        sleep(4)
    elif decisao0 == 2:
        vida = vida - 5
        print()
        sleep(2)
        print('<Narrador> O desconhecido fica enfurecido com a intimidação e da um tiro em seu pé.')
        print()
        sleep(1)
        print('<Narrador> Você levou 5 de dano.')
        checkVida()
        print()
        sleep(2)
        print('<Desconhecido> -Cale a boca!')
        print()
        sleep(2)
        print('<Desconhecido> -Estava com o pressentimento de que você iria vir até mim querendo ou não.')
        print()
        sleep(1)
        print('<Desconhecido> -Meu nome é PocketSquid.')
        print()
        sleep(2)
        print('<PoketSquid> -E eu mandei matar Steve como forma de vingança pela policia ter interferido nos meus negócios.')
        print()
        sleep(4)
    print('<Narrador> Após PoketSquid ter confessado o crime, ele julga que você estar la querendo prende-lo é uma ofensa.')
    print()
    sleep(2)
    print('<Narrador> Portanto ele da outro tiro.')
    print()
    sleep(2)
    print('<Narrador> E você leva mais 5 de dano.')
    vida = vida - 5
    checkVida()
    print()
    sleep(2)
    print("<Narrador> Depois do tiro, o chefe do crime decide atirar denovo para te matar, mas você consegue achar uma cobertura.")
    print()
    sleep(2)
    print('<Narrador> Sua decisão:')
    print()
    sleep(1)
    print('Vida Vilão = {}'.format(vidaChefe))
    print()
    sleep(1)
    print('1) Tentar acerta-lo com sua Laser Gun')
    print('2) Utilizar seu Dispositivo Hacker para atordoa-lo.')
    print()
    decisao01 = int(input())
    if decisao01 == 1:
        vidaChefe = vidaChefe - 50
        print()
        sleep(3)
        print('<Narrador> Você acertou o inimigo na perna, gerando 50 de dano.')
    elif decisao01 == 2:
        vidaChefe = vidaChefe - vidaChefe*0.7
        print()
        sleep(1)
        print('<Narrador> Ao hackea-lo você conseguiu fazer com que o sistema bionico dele trave, deixando-o livre para você acertar seu peito.')
        print()
        sleep(3)
        print('<Narrador> Esse ataque gerou 105 de dano.')
    print()
    sleep(2)
    print('<Narrador> PocketSquid tenta outro ataque, mas não foi efetivo.')
    print()
    sleep(2)
    print('<Narrador> Sua vez de agir, o que decidirá:')
    print()
    sleep(2)
    print('Vida Vilão = {}'.format(vidaChefe))
    print()
    print('1) Tentar um Headshot com a Laser Gun')
    print('2) Tentar inconcientiza-lo com uma granada elétrica')
    print()
    decisao02 = int(input())
    if decisao02 == 1:
        print()
        sleep(2)
        vidaChefe = vidaChefe - 80
        print('<Narrador> Você erra a cabeça, porém acerta o peito.')
        print()
        sleep(2)
        print('<Narrador> O chefe sobrevive ao tiro, entretanto, começa a sangrar.')
        print()
        sleep(2)
        print('<Narrador> O chefe sangra até morrer.')
    elif decisao02 == 2:
        vidaChefe = 0
        print()
        sleep(2)
        print('<Narrador> PoketSquid desvia da granada, mas ela o atinge mesmo assim.')
        print()
        sleep(2)
        print('<Narrador> Atordoado, o chefe se encontra muito vunerável, então você aproveita do momento e acerta um tiro na cabeça.')
        print()
        sleep(1)
        print('<Narrador> O chefe morre instantâneamente.')
    sleep(8)
    condicaoJogador = False

clear()
sleep(1)
print()
print()
print('/'*90)
print('LOADING...')
print('/'*90)
sleep(3)
print()
print()
print('<Narrador> Parabéns você terminou o jogo.')
print()
print()
sleep(4)

#PONTUAÇÃO
if xp >= 200:
    print('Você foi muito bem !!')
elif 200 > xp or xp > 150:
    print('Seu desempenho foi mediano')
else:
    print('Seu desempenho foi ruim...')

print()
sleep(1)
print('Sua pontuação foi de {} pontos.'.format(xp))
sleep(10)

clear()
sleep(2)
print()
print()

print('Créditos:')
print()
sleep(2)
print('João Pedro de Paula Oliveira do Amaral / Tia: 32049390 / 1G12 ')
print('Nicolas De Barros                      / Tia: 32070837 / 1G11 ')
print('Rafael Sergio Ruszki                   / Tia: 32075383 / 1G12 ')

print()
print()
sleep(5)
sair = input('Aperte "Enter" para sair.')
if sair == '':
    sys.exit()